# Generated by Django 4.1.7 on 2023-02-25 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('resellers', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='utils.address')),
                ('reseller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reseller', to='resellers.resellerprofile')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='vendors.vendorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
