# Generated by Django 4.1.7 on 2023-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(default='https://kuseka.s3.eu-west-2.amazonaws.com/images/assets/user.png'),
        ),
    ]
