# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_completion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refferal_code', models.CharField(default='1c7a4', max_length=255, unique=True)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_renewed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refferal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField(choices=[('NGN', 'Nigeria Naira'), ('GHS', 'Ghana Cedi'), ('KSH', 'Kenya Shilling'), ('UGX', 'Uganda Shilling')], max_length=10)),
                ('experience_periods', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_finished_basic_training', models.BooleanField(default=False)),
                ('basic_training_completion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bio', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('off_days', models.IntegerField(default=0)),
                ('push_notification_id', models.TextField(null=True)),
                ('jobs', models.ManyToManyField(related_name='jobs', to='resellers.job')),
                ('ratings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='resellers.rating')),
            ],
        ),
        migrations.CreateModel(
            name='JobConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activation_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('last_subscription_date', models.DateTimeField()),
                ('activation_location', models.TextField(null=True)),
                ('renewals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='resellers.renewal')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='conversions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='resellers.jobconversion'),
        ),
        migrations.AddField(
            model_name='job',
            name='softwares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='softwares', to='utils.software'),
        ),
        migrations.AddField(
            model_name='job',
            name='training_resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='utils.trainingresource'),
        ),
    ]
