# Generated by Django 4.1.7 on 2023-02-25 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_resources', models.TextField()),
                ('training_completion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refferal_code', models.CharField(max_length=255)),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('softwares', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='softwares', to='vendors.software')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_renewed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refferal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField(max_length=10)),
                ('experience_periods', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_finished_basic_training', models.BooleanField(default=False)),
                ('basic_training_completion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('off_days', models.IntegerField()),
                ('push_notification_id', models.TextField()),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='resellers.job')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='resellers.rating')),
            ],
        ),
        migrations.CreateModel(
            name='JobConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refferal_code', models.CharField(max_length=255)),
                ('activation_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('last_subscription_date', models.DateTimeField()),
                ('activation_location', models.TextField()),
                ('renewals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='resellers.renewal')),
            ],
        ),
    ]
