# Generated by Django 4.1.7 on 2023-02-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0002_alter_resellerprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellerprofile',
            name='off_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resellerprofile',
            name='push_notification_id',
            field=models.TextField(null=True),
        ),
    ]
