# Generated by Django 4.1.7 on 2023-02-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0003_alter_resellerprofile_off_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellerprofile',
            name='basic_training_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
