# Generated by Django 4.1.7 on 2023-02-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_software'),
        ('resellers', '0004_alter_resellerprofile_basic_training_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='softwares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='softwares', to='utils.software'),
        ),
    ]
