# Generated by Django 4.1.7 on 2023-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0005_alter_job_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='refferal_code',
            field=models.CharField(default='7bc1d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resellerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
