# Generated by Django 4.1.7 on 2023-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0006_alter_job_refferal_code_alter_resellerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='refferal_code',
            field=models.CharField(default='240cb', max_length=255, unique=True),
        ),
    ]
