# Generated by Django 4.1.7 on 2023-02-26 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0006_alter_job_commissions_alter_job_refferal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
