# Generated by Django 4.1.7 on 2023-02-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0007_job_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='conversions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='resellers.jobconversion'),
        ),
        migrations.AlterField(
            model_name='jobconversion',
            name='activation_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobconversion',
            name='refferal_code',
            field=models.CharField(default='74f8d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jobconversion',
            name='renewals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='resellers.renewal'),
        ),
    ]
