# Generated by Django 4.1.7 on 2023-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0012_alter_job_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='refferal_code',
            field=models.CharField(default='d9b67c', max_length=255, unique=True),
        ),
    ]
