# Generated by Django 4.1.7 on 2023-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0013_alter_job_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='refferal_code',
            field=models.CharField(default='e69439', max_length=255, unique=True),
        ),
    ]
