# Generated by Django 4.1.7 on 2023-03-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0014_alter_job_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='refferal_code',
            field=models.CharField(default='d7f925', max_length=255, unique=True),
        ),
    ]
