# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10)),
                ('currency', models.CharField(choices=[('GHANA', 'GH₵'), ('NIGERIA', 'NGN'), ('KENYA', 'KSH')], default='NIGERIA', max_length=20)),
                ('status', models.TextField(default=True)),
                ('idempotency_token', models.TextField(default='')),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
