# Generated by Django 4.1.6 on 2023-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.TextField(default=True),
        ),
    ]
