# Generated by Django 4.1.6 on 2023-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_amount_transactions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(auto_created=True),
        ),
    ]
