# Generated by Django 4.1.6 on 2023-02-20 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
