# Generated by Django 4.1.7 on 2023-02-25 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(default='')),
                ('title', models.CharField(max_length=255)),
                ('targets', models.TextField()),
                ('links', models.TextField()),
                ('sreenshots', models.TextField()),
                ('license_type', models.TextField()),
                ('software_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField(max_length=10)),
                ('settings', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('industry', models.TextField()),
                ('average_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='billing.plan')),
            ],
        ),
    ]
