# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('billing', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField(max_length=10)),
                ('industry', models.TextField(null=True)),
                ('average_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('vendor_email', models.CharField(max_length=255)),
                ('vendor_phone_number', models.CharField(max_length=20)),
                ('campaigns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.campaign')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='billing.plan')),
                ('softwares', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_softwares', to='utils.software')),
            ],
        ),
    ]
