# Generated by Django 4.1.7 on 2023-02-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_jobs'),
        ('utils', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='softwares',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='vendor_softwares', to='utils.software'),
        ),
    ]
