# Generated by Django 4.1.7 on 2023-02-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='settings',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='average_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='industry',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='billing.plan'),
        ),
    ]
