# Generated by Django 4.1.7 on 2023-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendorprofile_campaigns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='logo',
            field=models.TextField(default='https://kuseka.s3.eu-west-2.amazonaws.com/images/assets/company.png'),
        ),
    ]
