# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resellers', '0001_initial'),
        ('transactions', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('resellers_requested', models.IntegerField()),
                ('resellers_experince', models.IntegerField()),
                ('resellers_average_rating', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('industry', models.TextField()),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('estimated_reach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jobs', models.ManyToManyField(related_name='campaign_jobs', to='resellers.job')),
                ('softwares', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_softwares', to='utils.software')),
                ('training_resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_resources', to='utils.trainingresource')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='transactions.transaction')),
            ],
        ),
    ]
