# Generated by Django 4.1.7 on 2023-02-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('utils', '0002_software'),
        ('resellers', '0005_alter_job_softwares'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_jobs', to='resellers.job'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='resellers_average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='softwares',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_softwares', to='utils.software'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='training_resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_resources', to='campaigns.trainingresource'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='transactions.transaction'),
        ),
    ]
