# Generated by Django 4.1.7 on 2023-02-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0002_alter_job_refferal_code_alter_resellerprofile_jobs'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='campaign_jobs', to='resellers.job'),
        ),
    ]
