# Generated by Django 4.1.7 on 2023-02-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_trainingresource'),
        ('campaigns', '0002_alter_campaign_amount_alter_campaign_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='training_resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_resources', to='utils.trainingresource'),
        ),
        migrations.DeleteModel(
            name='TrainingResource',
        ),
    ]
