# Generated by Django 4.1.7 on 2023-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('campaigns', '0003_remove_campaign_softwares_campaign_softwares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='training_resources',
        ),
        migrations.AddField(
            model_name='campaign',
            name='training_resources',
            field=models.ManyToManyField(blank=True, related_name='training_resources', to='utils.trainingresource'),
        ),
    ]
