# Generated by Django 4.1.7 on 2023-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='license_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='type_of_software',
            field=models.TextField(default=''),
        ),
    ]
