# Generated by Django 4.1.7 on 2023-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_license_type_campaign_type_of_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
