# Generated by Django 4.1.7 on 2023-02-26 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('targets', models.TextField()),
                ('links', models.TextField()),
                ('sreenshots', models.TextField()),
                ('license_type', models.TextField()),
                ('software_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
