# Generated by Django 4.1.7 on 2023-02-26 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('targets', models.TextField()),
                ('links', models.TextField()),
                ('sreenshots', models.TextField()),
                ('license_type', models.TextField()),
                ('software_type', models.TextField()),
            ],
        ),
    ]
